### ISSUE TITLE
Support for Lerna Workspaces?

### ISSUE THREAD

**Issue by mrfambo** [ai/ssdeploy#3]
Alas, its being so hard for me to manage Monorepo. My folder structure is like this:

- .git
- projects
  - api
  - app1
  - app2

app1 goes to app1.domain.com and app2 goes to app2.domain.com. Api goes to Google Cloud App Engine 😝 Sorry if its complicated. But thats how things get complicated in real world i guess 😆 

How can i use ssdeploy to manage it?

**Comment by mrfambo** [comment]
My React Apps (app1 & app2) uses Websockets(socketio), and cloud run states it doesn't support websockets on inbound and i am not sure about the difference of inbound and outbound. 

https://cloud.google.com/run/docs/issues#grpc_websocket

**Comment by ai** [comment]
Feel free to send PR. It is important feature, but I do not need it, so you will need to help me.

**Comment by mrfambo** [comment]
Surely will try my level best <3
